/**
 * Handle exceptions the K6 way
 */
export declare const handleUnexpectedException: (error: string, testName: string) => void;
